stages:
  - test
  - deploy

variables:
  MYSQL_DATABASE: myapp_test
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: rootpassword

services:
  - name: mariadb:10.5
    alias: db
    command: ['--default-authentication-plugin=mysql_native_password']

before_script:
  - apt-get update -y
  - apt-get install -y curl
  - curl -sSL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install

test:
  stage: test
  image: ruby:3.1
  services:
    - mariadb:10.5
  script:
    - cp config/database.yml.gitlab-ci config/database.yml
    - bundle exec rails db:create RAILS_ENV=test
    - bundle exec rails db:schema:load RAILS_ENV=test
    - bundle exec rspec

#deploy:
#  stage: deploy
# image: ruby:3.1
#  script:
#    - ssh user@your-server "cd /path/to/app && git pull && bundle install && RAILS_ENV=production bundle exec rails db:migrate && RAILS_ENV=production bundle exec rails assets:precompile && touch tmp/restart.txt"
  only:
#    - main
