development:
  host: dc.example.com
  port: 389
  attribute: sAMAccountName
  base: dc=domain,dc=example,dc=com
# admin_user: "test"
# admin_password: P@ssw0rd
  admin_user: "directory"
  admin_password: 
  ssl: false
  #group_base: ou=Office_Users,dc=example,dc=org,dc=ua
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: 192.168.0.201
  port: 389
  attribute: sAMAccountName
  base: ou=Office_Users,dc=example,dc=org,dc=ua
  admin_user: "directory"
  admin_password: P@ssword
  ssl: false
  # <<: *AUTHORIZATIONS

