development:
  host: office.parallel.ua
  port: 389
  attribute: sAMAccountName
  base: dc=office,dc=parallel,dc=ua
# admin_user: "test"
# admin_password: P@ssw0rd
  admin_user: "directory"
  admin_password: amGe2Lgk0xTE
  ssl: false
  #group_base: ou=Office_Users,dc=office,dc=parallel,dc=ua
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: 192.168.0.207
  port: 389
  attribute: sAMAccountName
  base: ou=users,ou=Office_Users,dc=office,dc=parallel,dc=ua
  admin_user: "directory"
  admin_password: amGe2Lgk0xTE
  ssl: false
  # <<: *AUTHORIZATIONS
  #cn=boyko,dc=office,dc=parallel,dc=ua
