development:
  host: 192.168.0.207
  port: 389
  attribute: sAMAccountName
  base: dc=parallel,dc=ua
  admin_user: cn=boyko
  admin_password: 
  ssl: false
  group_base: ou=Users,ou=Office_Users,dc=office,dc=parallel,dc=ua
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: 192.168.0.207
  port: 389
  attribute: sAMAccountName
  base: dc=office,dc=parallel,dc=ua
  admin_user: cn=boyko
  admin_password: 
  ssl: false
  # <<: *AUTHORIZATIONS
